Vagrant.configure("2") do |config|
	config.vm.define "l2" do |l2|
		l2.vm.box = "Goldfingyr/UbuntuServer"
		l2.vm.network "private_network", ip: "192.168.11.2"
		l2.vm.provider "virtualbox" do |v|
		  v.memory = 2048
		  v.cpus = 1
		  v.name = "myUbuntu"
		end
	end
end
